name: fake-bge-module CI

on:
  push:
    branches:
      # Temporarily trigger only on "ci_testing" branch
      - ci_testing
      - master
    tags:
      - '[0-9]+'
  pull_request:

jobs:
  set_versions:
    name: Set build versions
    runs-on: ubuntu-latest
    outputs:
      module_version: ${{ steps.set_module_version.outputs.module_version }}
      file_version: ${{ steps.set_file_version.outputs.file_version }}
    steps:
      # Use ISO 8601 date (in UTC) + timestamp (in UTC)
      - name: Create generic module version
        run: echo ::set-env name=MODULE_VERSION::$(date -u +%Y%m%d).dev$(date -u +%H%M%S)

      # Use the tag name for a release
      - name: Override release module version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-env name=MODULE_VERSION::${GITHUB_REF#refs/*/}

      # Add addtional git sha ref
      - name: Override PR module version
        if: github.event_name == 'pull_request'
        run: echo ::set-env name=MODULE_VERSION::${MODULE_VERSION}+${GITHUB_SHA::8}

      # Set module version output
      - name: Set module version
        id: set_module_version
        run: echo ::set-output name=module_version::${MODULE_VERSION}

      # Use ISO 8601 timestamps (in UTC) for output/file version
      - name: Set file version
        id: set_file_version
        run: echo ::set-output name=file_version::$(date -u +%Y%m%dT%H%M%SZ)

  build_modules:
    name: Build modules
    runs-on: ubuntu-18.04
    needs: [set_versions]
    strategy:
      fail-fast: false
      matrix:
        upbge_version: ["0.2.5"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: UPBGE downloads cache
        uses: actions/cache@v2
        id: upbge-bin-cache
        with:
          path: upbge-bin
          key: upbge-binaries-${{ runner.os }}-${{ matrix.upbge_version }}-${{ hashFiles('**/tools/utils/download_upbge.sh') }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test fake_bge_module core module
        run: bash tests/run_pre_tests.sh src

      - name: Install UPBGE binary dependencies
        run: sudo apt-get install -y libglu1-mesa libjack0

      - name: Install fake-bge-module tools
        run: sudo apt-get install -y pandoc

      - name: Download UPBGE files
        if: steps.upbge-bin-cache.outputs.cache-hit != 'true'
        run: bash tools/utils/download_upbge.sh ${{ matrix.upbge_version }} upbge-bin

      - name: Checkout UPBGE from Github
        uses: actions/checkout@v2
        with:
          repository: "UPBGE/upbge"
          path: upbge

      - name: Generate pip Packages
        env:
          RELEASE_VERSION: ${{ needs.set_versions.outputs.module_version }}
        run: bash tools/pip_package/build_pip_package.sh release ${{ matrix.upbge_version }} ./upbge ./upbge-bin/upbge-v${{ matrix.upbge_version }}-bin

      - name: Archive pip packages
        uses: actions/upload-artifact@v2
        with:
          name: fake_bge_modules_${{ matrix.upbge_version}}_pip_${{ needs.set_versions.outputs.file_version }}
          path: release

      - name: Archive raw modules
        uses: actions/upload-artifact@v2
        with:
          name: fake_bge_modules_${{ matrix.upbge_version}}_raw_${{ needs.set_versions.outputs.file_version }}
          path: "raw_modules/fake_bge_module*"

      - name: Test Generated Modules
        run: bash tests/run_tests.sh raw_modules

      - name: Test generated pip module against Cycles addon
        # Using a wildcard instead of ${{ needs.set_versions.outputs.module_version }} below, because the pip filenames do not respect leading zeros:
        # For example: 00:29:45 UTC will create a file version "...dev2945-py3-none..." and not use {{ module_version}} "...dev002945-py3-none..."
        run: bash tests/pylint_cycles.sh ${{ matrix.upbge_version }} ./upbge/ ./release/${{ matrix.upbge_version }}/fake_bge_module_${{ matrix.upbge_version }}-*-py3-none-any.whl

  release_test:
    name: Release test
    needs: build_modules
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist

        # Publish to TestPyPi on each merge to master
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          password: ${{ secrets.test_pypi_token }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: "dist/fake_bge_modules_*_pip_*/*/"

  release:
    name: Release fake-bge-module
    needs: release_test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - name: Fetch Artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_ACTIONS }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Publish fake-bge-module to GitHub Release Page
        uses: csexton/release-asset-action@v2
        with:
          release-url: ${{ steps.create_release.outputs.upload_url }}
          pattern: "dist/fake_bge_modules_*_raw_*/*.zip"
          github-token: ${{ secrets.TOKEN_FOR_ACTIONS }}

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          password: ${{ secrets.pypi_token }}
          packages_dir: "dist/fake_bge_modules_*_pip_*/*/"